export const genres: string[] = [
  'Ação',
  'Aventura',
  'Cinema de arte',
  'Chanchada',
  'Comédia',
  'Comédia de ação',
  'Comédia de terror',
  'Comédia dramática',
  'Comédia romântica',
  'Dança',
  'Documentário',
  'Docuficção',
  'Drama',
  'Espionagem',
  'Faroeste',
  'Fantasia',
  'Fantasia científica',
  'Ficção científica',
  'Filmes com truques',
  'Filmes de guerra',
  'Mistério',
  'Musical',
  'Filme policial',
  'Romance',
  'Terror',
  'Thriller'
];
